name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install libxml2
        run: sudo apt-get install -y libxml2-utils

      - name: Run Tests
        run: ./test.sh

